server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.116.123.44:3306/qingyou?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: wiz
    password: wiz408
  mail:
    username: qingyou_serve@163.com
    password: ENTOSAYCQCKIRXCM
    host: smtp.163.com
  redis:
    port: 6379
    host: 1.116.123.44
    password: wizardry

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
